name: setup

on: push

jobs:
  setup:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Change files
      run: |
        PACKAGE_NAME=$(echo "${{github.event.repository.name}}" | sed -r "s|[^A-Za-z]+|-|g")

        sed -i -E 's|name": ".*?"|name": '"$PACKAGE_NAME"'"|g' package.json
        sed -i -E 's|repository": ".*?"|repository": "${{ github.event.repository.url }}"|g' package.json
        sed -i -E 's|author": ".*?"|author": "${{ github.event.repository.owner.login }}"|g' package.json

        rm -f .github/workflows/setup.yml

    - name: Push changes to github
      run: |
        git add -A
        git config --global user.name "${{ github.event.sender.login }}"
        git commit -m '[skip ci] Automatic setup of repo'
        git push origin ${{ github.ref }}
